### ISSUE TITLE
The plugin does not work, although LatePoint is installed and activated

### ISSUE THREAD

**Issue by uzunhair** [ashrafulsarkar/latepoint_manager#1]
a warning is displayed - To install and activate the LatePoint Manager extension version 1.1.0, it is required that the LatePoint version version 3.0.5 or higher is installed and activated.

I don't understand what could be the matter, can you help?

**Comment by ashrafulsarkar** [comment]
please share your login details my email: ashrafulsarkar47@gmail.com

**Comment by ashrafulsarkar** [comment]
Please check now. 1stly delete "Latepoint Manager" and then reinstall this plugin form WordPress.org. I hope all work parfectly.
Thank you.
